modLoader="javafml" #mandatory`
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}" #optional

[[mods]] #mandatory
modId="2bois_druidry" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="${mod_display_url}" #optional
logoFile="${mod_logo_file}" #optional
credits="${mod_credits}" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''





# Here's another dependency
[[dependencies.2bois_druidry]]
modId="minecraft"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.2bois_druidry]]
modId="irons_spellbooks" #mandatory
mandatory = true #mandatory
versionRange = "[1.21-3.5.0)" #mandatory
ordering = "AFTER"
side = "BOTH"

[[dependencies.2bois_druidry]]
modId="caelus"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[${caelus_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.2bois_druidry]]
modId="geckolib"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[${geckolib_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.2bois_druidry]]
modId="playeranimator"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[${player_animator_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.2bois_druidry]]
modId="playeranimator"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[${player_animator_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.2bois_druidry]]
modId="curios"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[9.0.5+1.21.0,)"
ordering="NONE"
side="BOTH"